### PR TITLE
Add documentation for resend invitation email

### PR DESCRIPTION
**Pull request by tdutrion**
Hi there!

Just getting to know the Slack API a bit better to answer an issue on a project I am just starting with :)

Say someone wants to resend the email whenever an already invited user ask for an invitation again (https://github.com/vluzrmos/lumen-slackin/issues/9), here's the documentation that helps the use case.

### CODE REVIEW

**Comment by ErikKalkoken** [comment]
Hi, thanks for your contribution. Just to clarify: Is this a new feature to the method that you are suggesting or is this an existing option that already works? Thanks

**Comment by tdutrion** [comment]
That's an existing working option that I looked up to enable the use case above in lumen-slackin. It does come with an error when the email has been sent recently, all documented here.

**Comment by ErikKalkoken** [comment]
ok, awesome! Thanks again!

**Comment by ErikKalkoken** [comment]
ok, awesome! Thanks again

**Comment by abinashmohanty** [comment]
Hey @tdutrion is the `resend invitation` function working right now? I'm facing the same issue and deployed using heroku but i can't get rid of its pending invitations module.

**Pull request merged**
