### PR TITLE
Updated required scope

### PR DESCRIPTION
**Pull request by cookstaar**

### CODE REVIEW

**Comment by ErikKalkoken** [comment]
This does not look right. The `client` scope relates to events and has apparently nothing to do with this method. check [here](https://api.slack.com/scopes/client)

**Comment by cookstaar** [comment]
I know it doesn't seem right, but I tried it and it works. First attempt
without that scope gave me an error and said I needed that scope. I went
through the OAuth dance and requested the client scope, and it worked. Not
sure if there are others but client definitely works.

Neil

**Comment by ErikKalkoken** [comment]
ok, I will add it. thanks for your contribution.

**Comment by cookstaar** [comment]
np. I'm guessing if or when this becomes an official api then the required
scope will change. They've probably just done the bare minimum to get
something out there.

Neil

**Pull request merged**
